[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
renet = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
